public enum EmployeeMenu {
    PRINT_ALL_CLIENTS,
    PRINT_ALL_CLUB_MEMBER,
    PRINT_CLIENTS_WITH_AT_LEAST_ONE_ORDER,
    PRINT_CLIENT_WITH_THE_LARGEST_SUM_ORDERS,
    ADDING_NEW_PRODUCT,
    CHANGING_PRODUCT_STATUS,
    MAKING_PURCHASE,
    LOGOUT
}
